version: '3'
services:
  kg-admin:
    image: registry.humanbrainproject.org/humanbrainproject/kg-core/kg-admin:latest
    ports:
      - 9110:9110
    environment:
      - EXTERNAL_PORT=9110
      - EXTERNAL_IP=${EXTERNAL_IP}
      - EUREKA_URI=http://${EXTERNAL_IP}:9500/eureka
      - ARANGO_HOST=${EXTERNAL_IP}
      - ARANGO_PORT=9111
      - ARANGO_PWD=changeMe
    depends_on:
      - arango

  arango:
    image: arangodb:3.4
    ports:
      - 9111:8529
    environment:
      - ARANGO_ROOT_PASSWORD=changeMe
    volumes:
      - /data/arango:/var/lib/arangodb3
    command: >
      --log.level queries=trace
#      - /data/arangoconf:/etc/arangodb3

  kg-authentication:
    image: registry.humanbrainproject.org/humanbrainproject/kg-core/kg-authentication:latest
    ports:
      - 9120:9120
    environment:
      - EXTERNAL_PORT=9120
      - EXTERNAL_IP=${EXTERNAL_IP}
      - EUREKA_URI=http://${EXTERNAL_IP}:9500/eureka
      - KEYCLOAK_SERVERURL=http://${EXTERNAL_IP}:9100/auth
      - KEYCLOAK_ROOTPWD=CHANGE_ME
      - KEYCLOAK_CLIENTSECRET=CHANGE_ME

  kg-core-api:
    image: registry.humanbrainproject.org/humanbrainproject/kg-core/kg-core-api:latest
    ports:
      - 9130:9130
    environment:
      - EXTERNAL_PORT=9130
      - EXTERNAL_IP=${EXTERNAL_IP}
      - ARANGO_HOST=${EXTERNAL_IP}
      - ARANGO_PORT=9141
      - ARANGO_PWD=changeMe
      - EUREKA_URI=http://${EXTERNAL_IP}:9500/eureka

  kg-graphdb-sync:
    image: registry.humanbrainproject.org/humanbrainproject/kg-core/kg-graphdb-sync:latest
    ports:
      - 9140:9140
    environment:
      - EUREKA_URI=http://${EXTERNAL_IP}:9500/eureka
      - EXTERNAL_IP=${EXTERNAL_IP}
      - EXTERNAL_PORT=9140
      - ARANGO_PWD=changeMe
      - ARANGO_HOST=${EXTERNAL_IP}
      - ARANGO_PORT=9111
    volumes:
      - /tmp/arango/log:/var/log/kg
    depends_on:
      - arango


  kg-graphdb-async:
    image: registry.humanbrainproject.org/humanbrainproject/kg-core/kg-graphdb-async:latest
    ports:
      - 9145:9145
    environment:
      - EUREKA_URI=http://${EXTERNAL_IP}:9500/eureka
      - EXTERNAL_IP=${EXTERNAL_IP}
      - EXTERNAL_PORT=9145
      - ARANGO_PWD=changeMe
      - ARANGO_HOST=${EXTERNAL_IP}
      - ARANGO_PORT=9111
    #volumes:
    #  - /tmp/arango/log:/var/log/kg
    #      - /tmp/arango:/var/lib/arangodb3
    depends_on:
      - arango

  kg-inference:
    image: registry.humanbrainproject.org/humanbrainproject/kg-core/kg-inference:latest
    ports:
      - 9150:9150
    environment:
      - EXTERNAL_PORT=9150
      - EXTERNAL_IP=${EXTERNAL_IP}
      - EUREKA_URI=http://${EXTERNAL_IP}:9500/eureka

  kg-jsonld:
    image: registry.humanbrainproject.org/humanbrainproject/kg-core/kg-jsonld:latest
    ports:
      - 9160:9160
    environment:
      - EUREKA_URI=http://${EXTERNAL_IP}:9500/eureka
      - EXTERNAL_IP=${EXTERNAL_IP}
      - EXTERNAL_PORT=9160
      - JAVA_OPTS=-Xms128m -Xmx256m

  kg-primarystore:
    image: registry.humanbrainproject.org/humanbrainproject/kg-core/kg-primarystore:latest
    ports:
      - 9180:9180
    environment:
      - EXTERNAL_PORT=9180
      - EXTERNAL_IP=${EXTERNAL_IP}
      - EUREKA_URI=http://${EXTERNAL_IP}:9500/eureka
      - ARANGO_PWD=changeMe
      - ARANGO_HOST=${EXTERNAL_IP}
      - ARANGO_PORT=9111
    depends_on:
      - arango

  kg-query:
    image: registry.humanbrainproject.org/humanbrainproject/kg-core/kg-query:latest
    ports:
      - 9190:9190
    environment:
      - EUREKA_URI=http://${EXTERNAL_IP}:9500/eureka
      - EXTERNAL_IP=${EXTERNAL_IP}
      - EXTERNAL_PORT=9190

  kg-releasing:
    image: registry.humanbrainproject.org/humanbrainproject/kg-core/kg-releasing:latest
    ports:
      - 9200:9200
    environment:
      - EUREKA_URI=http://${EXTERNAL_IP}:9500/eureka
      - EXTERNAL_IP=${EXTERNAL_IP}
      - EXTERNAL_PORT=9200

  kg-spatial-search:
    image: registry.humanbrainproject.org/humanbrainproject/kg-core/kg-spatial-search:latest
    ports:
      - 9210:9210
    environment:
      - EUREKA_URI=http://${EXTERNAL_IP}:9500/eureka
      - EXTERNAL_IP=${EXTERNAL_IP}
      - EXTERNAL_PORT=9210

  kg-indexing:
    image: registry.humanbrainproject.org/humanbrainproject/kg-core/kg-indexing:latest
    ports:
      - 9230:9230
    environment:
      - EUREKA_URI=http://${EXTERNAL_IP}:9500/eureka
      - EXTERNAL_IP=${EXTERNAL_IP}
      - EXTERNAL_PORT=9230

  kg-nexus-v0-adapter:
    image: registry.humanbrainproject.org/humanbrainproject/kg-core/kg-nexus-v0-adapter:latest
    ports:
      - 9240:9240
    environment:
      - EUREKA_URI=http://${EXTERNAL_IP}:9500/eureka
      - EXTERNAL_IP=${EXTERNAL_IP}
      - EXTERNAL_PORT=9240

  kg-nexus-v1-adapter:
    image: registry.humanbrainproject.org/humanbrainproject/kg-core/kg-nexus-v1-adapter:latest
    ports:
      - 9250:9250
    environment:
      - EUREKA_URI=http://${EXTERNAL_IP}:9500/eureka
      - EXTERNAL_IP=${EXTERNAL_IP}
      - EXTERNAL_PORT=9250
      - NEXUS_ENDPOINT=${NEXUS_ENDPOINT}
      - NEXUS_SA_TOKEN=${NEXUS_SA_TOKEN}

  kg-ids:
    image: registry.humanbrainproject.org/humanbrainproject/kg-core/kg-ids:latest
    ports:
      - 9260:9260
    environment:
      - EUREKA_URI=http://${EXTERNAL_IP}:9500/eureka
      - EXTERNAL_IP=${EXTERNAL_IP}
      - EXTERNAL_PORT=9260
      - ARANGO_PWD=changeMe
      - ARANGO_HOST=${EXTERNAL_IP}
      - ARANGO_PORT=9111
    depends_on:
      - arango

  keycloak:
    image: jboss/keycloak:6.0.1
    ports:
      - 9100:8080
    environment:
      - KEYCLOAK_USER=root
      - KEYCLOAK_PASSWORD=CHANGE_ME
      - jboss.bind.address.management=0.0.0.0
      - jboss.bind.address=0.0.0.0