version: '3'
services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9501:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.portainer_data:/data

  kg-service-discovery:
    image: registry.humanbrainproject.org/humanbrainproject/kg-core/kg-service-discovery:latest
    ports:
      - 9500:9500
    environment:
      - EXTERNAL_IP=${EXTERNAL_IP}
      - EXTERNAL_PORT=9500
